# Generated by Django 5.0.7 on 2024-09-02 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhafera', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listuser',
            old_name='list_order',
            new_name='list_position',
        ),
        migrations.AlterField(
            model_name='listuser',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listusers', to='adhafera.list'),
        ),
    ]
